# Generated by Django 5.0 on 2024-02-02 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='product_name')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='product_image')),
                ('description', models.TextField(blank=True, verbose_name='product_description')),
                ('short_desc', models.CharField(blank=True, max_length=100, verbose_name='short description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='product_price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='product_quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
